# Generated by Django 3.2 on 2022-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_oxygenavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygenavailability',
            name='oxygen_type',
            field=models.CharField(choices=[('CGS', 'Compressed Gas System'), ('POC', 'Portable Oxygen Concentrators'), ('LOS', 'Liquid Oxygen Systems')], default='CGS', max_length=4),
        ),
    ]
